import turtle
wn=turtle.Screen()
wn.bgcolor("blue")
tess=turtle.Turtle()
tess.color("white")
tess.pensize(3)
# tess.forward(50)
# tess.left(50)
# tess.forward(50)
# tess.left(100)
# tess.forward(50)
# tess.left(45)
# tess.forward(50)
# tess.left(90)
# tess.forward(50)
tess.right(90)
tess.forward(50)
tess.left(90)
tess.forward(50)
tess.left(90)
tess.forward(50)
tess.left(30)
tess.forward(50)
tess.left(120)
tess.forward(50)
	
wn.exitonclick()